# https://jupyterbook.org/customize/config.html

title                       : Sphinx Code Highlighter
author                      : ""                             # goes in the footer
exclude_patterns            : [_build, Thumbs.db, .DS_Store]

repository                  :
  url                       : https://github.com/alissa-huskey/sphinx-code-highlighter
  path_to_book              : docs
  branch                    : main

execute                     :
  execute_notebooks         : off

html                        :
  use_issues_button         : true
  use_repository_button     : true
  use_edit_page_button      : false
  use_download_button       : false
  favicon                   : ""
  extra_navbar              : ""
  extra_footer              : ""
  baseurl                   : ""

launch_buttons              :
  binderhub_url             : ""
  thebe                     : false

sphinx                      :
  config                    :
    version                 : 0.0.1
    html_show_copyright     : false
  extra_extensions          :
                              - code_highlighter
                              - sphinx_panels
